# Generated by Django 2.1 on 2018-08-18 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0004_auto_20180818_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(default='', max_length=10000)),
                ('config', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_item', to='alfa.Config')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='config',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='alfa.Config'),
        ),
        migrations.AddField(
            model_name='dataitem',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_item', to='alfa.Project'),
        ),
    ]
